---

- name: full system upgrade
  pacman:
    update_cache: yes
    upgrade: yes


- name: install standard packages
  pacman:
    name: "{{ packages | default(default_packages) }}"


- name: check if zsh is present
  stat:
    path: /bin/zsh
  register: zsh


- name: set root's shell to zsh
  user:
    name: root
    shell: /bin/zsh
  when: zsh.stat.exists


- name: set up sudo
  pacman:
    name: sudo


- name: create non root user
  user:
    name: "{{ admin_acc }}"
    shell: /bin/zsh
    groups: wheel
    append: yes


- name: add ssh key
  authorized_key:
    user: "{{ admin_acc }}"
    state: present
    manage_dir: yes
    key: "{{ lookup('file', admin_acc_pubkey) }}"


- name: Allow wheel group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: visudo -cf %s 

